// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901035417_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.ActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<Guid?>("CarriedFromId")
                        .HasColumnType("uuid")
                        .HasColumnName("carried_from_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("RetroCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("retro_card_id");

                    b.Property<Guid?>("RetroSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("retro_session_id");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TalkingPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("talking_point_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_action_items");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_action_items_assignee_id");

                    b.HasIndex("CarriedFromId")
                        .HasDatabaseName("ix_action_items_carried_from_id");

                    b.HasIndex("RetroCardId")
                        .HasDatabaseName("ix_action_items_retro_card_id");

                    b.HasIndex("RetroSessionId")
                        .HasDatabaseName("ix_action_items_retro_session_id");

                    b.HasIndex("SprintId")
                        .HasDatabaseName("ix_action_items_sprint_id");

                    b.HasIndex("TalkingPointId")
                        .HasDatabaseName("ix_action_items_talking_point_id");

                    b.ToTable("action_items", null, t =>
                        {
                            t.HasCheckConstraint("action_items_scope_check", "sprint_id is not null or retro_session_id is not null");

                            t.HasCheckConstraint("action_items_status_check", "status in ('open', 'in_progress', 'done', 'carried_over', 'dropped')");

                            t.HasCheckConstraint("action_items_type_check", "type in ('retro', 'planning')");
                        });
                });

            modelBuilder.Entity("Backend.Models.Blocker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("JiraIssueId")
                        .HasColumnType("text")
                        .HasColumnName("jira_issue_id");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("RaisedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("raised_by");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_blockers");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_blockers_owner_id");

                    b.HasIndex("RaisedBy")
                        .HasDatabaseName("ix_blockers_raised_by");

                    b.HasIndex("SprintId")
                        .HasDatabaseName("ix_blockers_sprint_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_blockers_team_id");

                    b.ToTable("blockers", null, t =>
                        {
                            t.HasCheckConstraint("blockers_status_check", "status in ('Open', 'InProgress', 'Resolved')");
                        });
                });

            modelBuilder.Entity("Backend.Models.FocusTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_focus_topics");

                    b.HasIndex("SprintId")
                        .HasDatabaseName("ix_focus_topics_sprint_id");

                    b.ToTable("focus_topics", null, t =>
                        {
                            t.HasCheckConstraint("focus_topics_status_check", "status in ('on_track', 'at_risk', 'on_hold', 'done')");
                        });
                });

            modelBuilder.Entity("Backend.Models.Icebreaker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_icebreakers");

                    b.ToTable("icebreakers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000001"),
                            Category = "quick",
                            Source = "seeded",
                            Text = "What's one thing you're looking forward to this week?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000002"),
                            Category = "fun",
                            Source = "seeded",
                            Text = "If you could have any superpower for just today, what would it be?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000003"),
                            Category = "team-building",
                            Source = "seeded",
                            Text = "What's the best piece of advice you've ever received?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000004"),
                            Category = "team-building",
                            Source = "seeded",
                            Text = "What's a skill you've picked up in the last year that surprised you?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000005"),
                            Category = "retro",
                            Source = "seeded",
                            Text = "If your current project was a movie, what genre would it be?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000006"),
                            Category = "quick",
                            Source = "seeded",
                            Text = "What emoji best describes how you're feeling right now?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000007"),
                            Category = "fun",
                            Source = "seeded",
                            Text = "What's one thing outside of work you've been enjoying lately?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000008"),
                            Category = "team-building",
                            Source = "seeded",
                            Text = "What's your go-to strategy when you're stuck on a hard problem?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000009"),
                            Category = "retro",
                            Source = "seeded",
                            Text = "If the sprint was a road trip, where did we end up vs. where we planned to go?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000010"),
                            Category = "retro",
                            Source = "seeded",
                            Text = "What's one word that describes last sprint?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000011"),
                            Category = "team-building",
                            Source = "seeded",
                            Text = "What's a tool or shortcut you've discovered recently that saves you time?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000012"),
                            Category = "team-building",
                            Source = "seeded",
                            Text = "What's the most interesting thing you've learned in the last two weeks?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000013"),
                            Category = "retro",
                            Source = "seeded",
                            Text = "If you could change one thing about how the team communicates, what would it be?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000014"),
                            Category = "fun",
                            Source = "seeded",
                            Text = "What's something small that made your day better recently?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000015"),
                            Category = "fun",
                            Source = "seeded",
                            Text = "If you had a theme song that played when you entered a room, what would it be?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000016"),
                            Category = "team-building",
                            Source = "seeded",
                            Text = "What's the most challenging part of remote/hybrid work for you?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000017"),
                            Category = "team-building",
                            Source = "seeded",
                            Text = "What's a technical concept you wish you had learned earlier in your career?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000018"),
                            Category = "fun",
                            Source = "seeded",
                            Text = "What's the last thing that made you laugh out loud?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000019"),
                            Category = "fun",
                            Source = "seeded",
                            Text = "If the team was a band, what instrument would each person play?"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000020"),
                            Category = "quick",
                            Source = "seeded",
                            Text = "What's one habit you're trying to build or break right now?"
                        });
                });

            modelBuilder.Entity("Backend.Models.JiraIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token_encrypted");

                    b.Property<string>("CloudId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cloud_id");

                    b.Property<string>("CloudName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cloud_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RefreshTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_encrypted");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.HasKey("Id")
                        .HasName("pk_jira_integrations");

                    b.HasIndex("TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_jira_integrations_team_id");

                    b.ToTable("jira_integrations", (string)null);
                });

            modelBuilder.Entity("Backend.Models.MoodCheckin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("EntryMood")
                        .HasColumnType("integer")
                        .HasColumnName("entry_mood");

                    b.Property<int?>("ExitMood")
                        .HasColumnType("integer")
                        .HasColumnName("exit_mood");

                    b.Property<Guid>("RetroSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("retro_session_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mood_checkins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mood_checkins_user_id");

                    b.HasIndex("RetroSessionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_mood_checkins_retro_session_id_user_id");

                    b.ToTable("mood_checkins", null, t =>
                        {
                            t.HasCheckConstraint("mood_checkins_entry_mood_check", "entry_mood between 1 and 5");

                            t.HasCheckConstraint("mood_checkins_exit_mood_check", "exit_mood between 1 and 5");
                        });
                });

            modelBuilder.Entity("Backend.Models.PlatformAdmin", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.HasKey("UserId")
                        .HasName("pk_platform_admins");

                    b.HasIndex("GrantedBy")
                        .HasDatabaseName("ix_platform_admins_granted_by");

                    b.ToTable("platform_admins", (string)null);
                });

            modelBuilder.Entity("Backend.Models.PlatformAdminAllowlist", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.HasKey("Email")
                        .HasName("pk_platform_admin_allowlist");

                    b.ToTable("platform_admin_allowlist", null, t =>
                        {
                            t.HasCheckConstraint("platform_admin_allowlist_email_lowercase", "email = lower(email)");
                        });

                    b.HasData(
                        new
                        {
                            Email = "maxime.beaulieu@amilia.com",
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "bootstrap admin — migration 019"
                        });
                });

            modelBuilder.Entity("Backend.Models.PokerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_ticket_id");

                    b.Property<string>("CustomDeckJson")
                        .HasColumnType("text")
                        .HasColumnName("custom_deck_json");

                    b.Property<string>("DeckType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deck_type");

                    b.Property<Guid?>("FacilitatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("facilitator_id");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_poker_sessions");

                    b.HasIndex("FacilitatorId")
                        .HasDatabaseName("ix_poker_sessions_facilitator_id");

                    b.HasIndex("SprintId")
                        .IsUnique()
                        .HasDatabaseName("ix_poker_sessions_sprint_id");

                    b.ToTable("poker_sessions", null, t =>
                        {
                            t.HasCheckConstraint("poker_sessions_deck_type_check", "deck_type in ('Fibonacci', 'TShirt', 'Custom')");

                            t.HasCheckConstraint("poker_sessions_status_check", "status in ('Pending', 'InProgress', 'Completed')");
                        });
                });

            modelBuilder.Entity("Backend.Models.PokerTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("FinalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("final_points");

                    b.Property<string>("JiraIssueId")
                        .HasColumnType("text")
                        .HasColumnName("jira_issue_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("PokerSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("poker_session_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<bool>("VotesRevealed")
                        .HasColumnType("boolean")
                        .HasColumnName("votes_revealed");

                    b.HasKey("Id")
                        .HasName("pk_poker_tickets");

                    b.HasIndex("PokerSessionId")
                        .HasDatabaseName("ix_poker_tickets_poker_session_id");

                    b.ToTable("poker_tickets", (string)null);
                });

            modelBuilder.Entity("Backend.Models.PokerVote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Estimate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estimate");

                    b.Property<Guid>("PokerTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("poker_ticket_id");

                    b.Property<DateTime?>("RevealedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revealed_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_poker_votes");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_poker_votes_user_id");

                    b.HasIndex("PokerTicketId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_poker_votes_poker_ticket_id_user_id");

                    b.ToTable("poker_votes", (string)null);
                });

            modelBuilder.Entity("Backend.Models.RecurringAgendaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("LastStatus")
                        .HasColumnType("text")
                        .HasColumnName("last_status");

                    b.Property<int?>("SnoozedUntilSprintNumber")
                        .HasColumnType("integer")
                        .HasColumnName("snoozed_until_sprint_number");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_recurring_agenda_items");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_recurring_agenda_items_team_id");

                    b.ToTable("recurring_agenda_items", (string)null);
                });

            modelBuilder.Entity("Backend.Models.RetroCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Column")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("column");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiscussionNotes")
                        .HasColumnType("text")
                        .HasColumnName("discussion_notes");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("GroupLabel")
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("group_label");

                    b.Property<bool>("IsDiscussed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_discussed");

                    b.Property<bool>("IsRevealed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revealed");

                    b.Property<Guid>("RetroSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("retro_session_id");

                    b.HasKey("Id")
                        .HasName("pk_retro_cards");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_retro_cards_author_id");

                    b.HasIndex("RetroSessionId")
                        .HasDatabaseName("ix_retro_cards_retro_session_id");

                    b.ToTable("retro_cards", (string)null);
                });

            modelBuilder.Entity("Backend.Models.RetroParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymous");

                    b.Property<bool>("IsHost")
                        .HasColumnType("boolean")
                        .HasColumnName("is_host");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("RetroSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("retro_session_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_retro_participants");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_retro_participants_user_id");

                    b.HasIndex("RetroSessionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_retro_participants_retro_session_id_user_id");

                    b.ToTable("retro_participants", (string)null);
                });

            modelBuilder.Entity("Backend.Models.RetroSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ActiveDiscussionCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_discussion_card_id");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("columns_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentSpeakerId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_speaker_id");

                    b.Property<Guid?>("FacilitatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("facilitator_id");

                    b.Property<bool>("HideVotesUntilRevealed")
                        .HasColumnType("boolean")
                        .HasColumnName("hide_votes_until_revealed");

                    b.Property<string>("IcebreakerQuestion")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("icebreaker_question");

                    b.Property<string>("InviteCode")
                        .HasColumnType("text")
                        .HasColumnName("invite_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<bool>("SkipIcebreaker")
                        .HasColumnType("boolean")
                        .HasColumnName("skip_icebreaker");

                    b.Property<bool>("SkipMoodCheckins")
                        .HasColumnType("boolean")
                        .HasColumnName("skip_mood_checkins");

                    b.Property<string>("SpeakerOrderJson")
                        .HasColumnType("text")
                        .HasColumnName("speaker_order_json");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer")
                        .HasColumnName("vote_count");

                    b.HasKey("Id")
                        .HasName("pk_retro_sessions");

                    b.HasIndex("FacilitatorId")
                        .HasDatabaseName("ix_retro_sessions_facilitator_id");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("ix_retro_sessions_invite_code");

                    b.HasIndex("SprintId")
                        .IsUnique()
                        .HasDatabaseName("retro_sessions_sprint_id_key")
                        .HasFilter("sprint_id is not null");

                    b.ToTable("retro_sessions", null, t =>
                        {
                            t.HasCheckConstraint("retro_sessions_phase_check", "phase in ('CheckIn', 'Icebreaker', 'Write', 'Group', 'Vote', 'Discuss', 'WrapUp', 'Completed')");
                        });
                });

            modelBuilder.Entity("Backend.Models.RetroTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("columns_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsBuiltin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_builtin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_retro_templates");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_retro_templates_created_by");

                    b.ToTable("retro_templates", (string)null);
                });

            modelBuilder.Entity("Backend.Models.RetroVote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<Guid>("RetroCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("retro_card_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_retro_votes");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_retro_votes_user_id");

                    b.HasIndex("RetroCardId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_retro_votes_retro_card_id_user_id");

                    b.ToTable("retro_votes", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("Assignment")
                        .HasColumnType("text")
                        .HasColumnName("assignment");

                    b.Property<string>("Facing")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("facing");

                    b.Property<bool>("HasDock")
                        .HasColumnType("boolean")
                        .HasColumnName("has_dock");

                    b.Property<bool>("HasTerminal")
                        .HasColumnType("boolean")
                        .HasColumnName("has_terminal");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("OccupantId")
                        .HasColumnType("uuid")
                        .HasColumnName("occupant_id");

                    b.Property<string>("OccupantName")
                        .HasColumnType("text")
                        .HasColumnName("occupant_name");

                    b.Property<bool>("OutOfService")
                        .HasColumnType("boolean")
                        .HasColumnName("out_of_service");

                    b.Property<string>("Pod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pod");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer")
                        .HasColumnName("seat_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seats");

                    b.HasIndex("OccupantId")
                        .HasDatabaseName("seats_occupant_idx");

                    b.HasIndex("SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_seats_seat_number");

                    b.ToTable("seats", null, t =>
                        {
                            t.HasCheckConstraint("seats_assignment_check", "assignment in ('permanent', 'floating')");

                            t.HasCheckConstraint("seats_assignment_consistency", "(occupant_id is null and assignment is null) or (occupant_id is not null and assignment is not null)");

                            t.HasCheckConstraint("seats_facing_check", "facing in ('N', 'E', 'S', 'W')");

                            t.HasCheckConstraint("seats_pod_check", "pod in ('HEX', 'A', 'B', 'C', 'D', 'E', 'F')");
                        });
                });

            modelBuilder.Entity("Backend.Models.SeatDefectReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by");

                    b.Property<string>("ReporterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reporter_name");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolution_note");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_seat_defect_reports");

                    b.HasIndex("ClosedBy")
                        .HasDatabaseName("ix_seat_defect_reports_closed_by");

                    b.HasIndex("ReportedBy")
                        .HasDatabaseName("ix_seat_defect_reports_reported_by");

                    b.HasIndex("SeatId")
                        .HasDatabaseName("seat_defect_reports_seat_idx");

                    b.HasIndex("Status")
                        .HasDatabaseName("seat_defect_reports_status_idx");

                    b.ToTable("seat_defect_reports", null, t =>
                        {
                            t.HasCheckConstraint("seat_defect_reports_status_check", "status in ('open', 'closed')");
                        });
                });

            modelBuilder.Entity("Backend.Models.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ChampionId")
                        .HasColumnType("uuid")
                        .HasColumnName("champion_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Goal")
                        .HasColumnType("text")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PreviousGoal")
                        .HasColumnType("text")
                        .HasColumnName("previous_goal");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_sprints");

                    b.HasIndex("ChampionId")
                        .HasDatabaseName("ix_sprints_champion_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_sprints_team_id");

                    b.ToTable("sprints", null, t =>
                        {
                            t.HasCheckConstraint("sprints_status_check", "status in ('planning', 'active', 'completed')");
                        });
                });

            modelBuilder.Entity("Backend.Models.SprintMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("CapacityScore")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_score");

                    b.Property<string>("DaysOff")
                        .HasColumnType("text")
                        .HasColumnName("days_off");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sprint_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sprint_members_user_id");

                    b.HasIndex("SprintId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_sprint_members_sprint_id_user_id");

                    b.ToTable("sprint_members", null, t =>
                        {
                            t.HasCheckConstraint("sprint_members_capacity_score_check", "capacity_score between 1 and 10");
                        });
                });

            modelBuilder.Entity("Backend.Models.SprintTraining", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sprint_trainings");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sprint_trainings_user_id");

                    b.HasIndex("SprintId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_sprint_trainings_sprint_id_user_id");

                    b.ToTable("sprint_trainings", (string)null);
                });

            modelBuilder.Entity("Backend.Models.TalkingPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AgendaItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("agenda_item_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FocusTopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("focus_topic_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_talking_points");

                    b.HasIndex("AgendaItemId")
                        .HasDatabaseName("ix_talking_points_agenda_item_id");

                    b.HasIndex("FocusTopicId")
                        .HasDatabaseName("ix_talking_points_focus_topic_id");

                    b.ToTable("talking_points", null, t =>
                        {
                            t.HasCheckConstraint("talking_point_has_one_parent", "(focus_topic_id is not null)::int + (agenda_item_id is not null)::int = 1");
                        });
                });

            modelBuilder.Entity("Backend.Models.TalkingPointNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TalkingPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("talking_point_id");

                    b.HasKey("Id")
                        .HasName("pk_talking_point_notes");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_talking_point_notes_author_id");

                    b.HasIndex("TalkingPointId")
                        .HasDatabaseName("ix_talking_point_notes_talking_point_id");

                    b.ToTable("talking_point_notes", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SprintTerm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sprint_term");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_teams_created_by");

                    b.ToTable("teams", null, t =>
                        {
                            t.HasCheckConstraint("teams_name_length", "char_length(name) <= 100");

                            t.HasCheckConstraint("teams_sprint_term_length", "char_length(sprint_term) <= 30");
                        });
                });

            modelBuilder.Entity("Backend.Models.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_team_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_team_members_user_id");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_team_members_team_id_user_id");

                    b.ToTable("team_members", null, t =>
                        {
                            t.HasCheckConstraint("team_members_role_check", "role in ('member', 'admin')");
                        });
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid?>("EntraObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("entra_object_id");

                    b.Property<Guid?>("EntraTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("entra_tenant_id");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymous");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EntraObjectId")
                        .IsUnique()
                        .HasDatabaseName("users_entra_object_id_key")
                        .HasFilter("entra_object_id is not null");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("users_guest_has_no_entra_id", "not is_anonymous or entra_object_id is null");
                        });
                });

            modelBuilder.Entity("Backend.Models.ActionItem", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_action_items_users_assignee_id");

                    b.HasOne("Backend.Models.ActionItem", null)
                        .WithMany()
                        .HasForeignKey("CarriedFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_action_items_action_items_carried_from_id");

                    b.HasOne("Backend.Models.RetroCard", null)
                        .WithMany()
                        .HasForeignKey("RetroCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_action_items_retro_cards_retro_card_id");

                    b.HasOne("Backend.Models.RetroSession", null)
                        .WithMany()
                        .HasForeignKey("RetroSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_action_items_retro_sessions_retro_session_id");

                    b.HasOne("Backend.Models.Sprint", null)
                        .WithMany("ActionItems")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_action_items_sprints_sprint_id");

                    b.HasOne("Backend.Models.TalkingPoint", null)
                        .WithMany("ActionItems")
                        .HasForeignKey("TalkingPointId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_action_items_talking_points_talking_point_id");
                });

            modelBuilder.Entity("Backend.Models.Blocker", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_blockers_users_owner_id");

                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RaisedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_blockers_users_raised_by");

                    b.HasOne("Backend.Models.Sprint", null)
                        .WithMany("Blockers")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_blockers_sprints_sprint_id");

                    b.HasOne("Backend.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blockers_teams_team_id");
                });

            modelBuilder.Entity("Backend.Models.FocusTopic", b =>
                {
                    b.HasOne("Backend.Models.Sprint", null)
                        .WithMany("FocusTopics")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_focus_topics_sprints_sprint_id");
                });

            modelBuilder.Entity("Backend.Models.JiraIntegration", b =>
                {
                    b.HasOne("Backend.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jira_integrations_teams_team_id");
                });

            modelBuilder.Entity("Backend.Models.MoodCheckin", b =>
                {
                    b.HasOne("Backend.Models.RetroSession", null)
                        .WithMany("MoodCheckins")
                        .HasForeignKey("RetroSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mood_checkins_retro_sessions_retro_session_id");

                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mood_checkins_users_user_id");
                });

            modelBuilder.Entity("Backend.Models.PlatformAdmin", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_platform_admins_users_granted_by");

                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_platform_admins_users_user_id");
                });

            modelBuilder.Entity("Backend.Models.PokerSession", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("FacilitatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_poker_sessions_users_facilitator_id");

                    b.HasOne("Backend.Models.Sprint", null)
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poker_sessions_sprints_sprint_id");
                });

            modelBuilder.Entity("Backend.Models.PokerTicket", b =>
                {
                    b.HasOne("Backend.Models.PokerSession", null)
                        .WithMany("Tickets")
                        .HasForeignKey("PokerSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poker_tickets_poker_sessions_poker_session_id");
                });

            modelBuilder.Entity("Backend.Models.PokerVote", b =>
                {
                    b.HasOne("Backend.Models.PokerTicket", null)
                        .WithMany("Votes")
                        .HasForeignKey("PokerTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poker_votes_poker_tickets_poker_ticket_id");

                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_poker_votes_users_user_id");
                });

            modelBuilder.Entity("Backend.Models.RecurringAgendaItem", b =>
                {
                    b.HasOne("Backend.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_agenda_items_teams_team_id");
                });

            modelBuilder.Entity("Backend.Models.RetroCard", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_retro_cards_users_author_id");

                    b.HasOne("Backend.Models.RetroSession", null)
                        .WithMany("Cards")
                        .HasForeignKey("RetroSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retro_cards_retro_sessions_retro_session_id");
                });

            modelBuilder.Entity("Backend.Models.RetroParticipant", b =>
                {
                    b.HasOne("Backend.Models.RetroSession", null)
                        .WithMany("Participants")
                        .HasForeignKey("RetroSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retro_participants_retro_sessions_retro_session_id");

                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_retro_participants_users_user_id");
                });

            modelBuilder.Entity("Backend.Models.RetroSession", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("FacilitatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_retro_sessions_users_facilitator_id");

                    b.HasOne("Backend.Models.Sprint", null)
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_retro_sessions_sprints_sprint_id");
                });

            modelBuilder.Entity("Backend.Models.RetroTemplate", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_retro_templates_users_created_by");
                });

            modelBuilder.Entity("Backend.Models.RetroVote", b =>
                {
                    b.HasOne("Backend.Models.RetroCard", null)
                        .WithMany("Votes")
                        .HasForeignKey("RetroCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retro_votes_retro_cards_retro_card_id");

                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_retro_votes_users_user_id");
                });

            modelBuilder.Entity("Backend.Models.Seat", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OccupantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_seats_users_occupant_id");
                });

            modelBuilder.Entity("Backend.Models.SeatDefectReport", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ClosedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_seat_defect_reports_users_closed_by");

                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seat_defect_reports_users_reported_by");

                    b.HasOne("Backend.Models.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seat_defect_reports_seats_seat_id");
                });

            modelBuilder.Entity("Backend.Models.Sprint", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sprints_users_champion_id");

                    b.HasOne("Backend.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sprints_teams_team_id");
                });

            modelBuilder.Entity("Backend.Models.SprintMember", b =>
                {
                    b.HasOne("Backend.Models.Sprint", null)
                        .WithMany("SprintMembers")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sprint_members_sprints_sprint_id");

                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sprint_members_users_user_id");
                });

            modelBuilder.Entity("Backend.Models.SprintTraining", b =>
                {
                    b.HasOne("Backend.Models.Sprint", null)
                        .WithMany("Trainings")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sprint_trainings_sprints_sprint_id");

                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sprint_trainings_users_user_id");
                });

            modelBuilder.Entity("Backend.Models.TalkingPoint", b =>
                {
                    b.HasOne("Backend.Models.RecurringAgendaItem", null)
                        .WithMany("TalkingPoints")
                        .HasForeignKey("AgendaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_talking_points_recurring_agenda_items_agenda_item_id");

                    b.HasOne("Backend.Models.FocusTopic", null)
                        .WithMany("TalkingPoints")
                        .HasForeignKey("FocusTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_talking_points_focus_topics_focus_topic_id");
                });

            modelBuilder.Entity("Backend.Models.TalkingPointNote", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_talking_point_notes_users_author_id");

                    b.HasOne("Backend.Models.TalkingPoint", null)
                        .WithMany("Notes")
                        .HasForeignKey("TalkingPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_talking_point_notes_talking_points_talking_point_id");
                });

            modelBuilder.Entity("Backend.Models.Team", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teams_users_created_by");
                });

            modelBuilder.Entity("Backend.Models.TeamMember", b =>
                {
                    b.HasOne("Backend.Models.Team", null)
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_teams_team_id");

                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_users_user_id");
                });

            modelBuilder.Entity("Backend.Models.FocusTopic", b =>
                {
                    b.Navigation("TalkingPoints");
                });

            modelBuilder.Entity("Backend.Models.PokerSession", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Backend.Models.PokerTicket", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Backend.Models.RecurringAgendaItem", b =>
                {
                    b.Navigation("TalkingPoints");
                });

            modelBuilder.Entity("Backend.Models.RetroCard", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Backend.Models.RetroSession", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("MoodCheckins");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Backend.Models.Sprint", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Blockers");

                    b.Navigation("FocusTopics");

                    b.Navigation("SprintMembers");

                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("Backend.Models.TalkingPoint", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Backend.Models.Team", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
